name: Github app token testing

on:
  workflow_dispatch:
    inputs:
      jfrog_url:
        description: 'URL of Artifactory server'
        type: string
        default: 'https://nethermind.jfrog.io'
      CHART_PATH:
        description: 'Chart path'
        type: string
        required: true
        default: "chart/karpenter-node/"
      CHART_FILENAME:
        description: "Name of chart.yaml file"
        type: string
        default: "Chart.yaml"

permissions:
  id-token: write
  attestations: write
  contents: write  
  pull-requests: write  

jobs:
  saas_github:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5.0.1

      - name: Generate GitHub App installation token
        id: gh_app_token
        env:
          APP_ID: ${{ secrets.APP_ID }}
          INSTALLATION_ID: ${{ secrets.INSTALLATION_ID }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          echo "Generating JWT..."

          # Install jwt-cli
          sudo npm install -g jwt-cli

          # Write private key to a PEM file
          echo "$PRIVATE_KEY" > key.pem
          sed -i 's/\\n/\n/g' key.pem
          chmod 600 key.pem

          # Create JWT (correct flags)
          JWT=$(jwt encode \
           --secret @key.pem \
            --alg RS256 \
            '{
              "iat": '"$(date +%s)"',
              "exp": '"$(($(date +%s)+600))"',
              "iss": "$APP_ID"
            }')

          echo "JWT=$JWT"

          echo "Requesting installation token..."
          TOKEN=$(curl -s -X POST \
            -H "Authorization: Bearer $JWT" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/app/installations/$INSTALLATION_ID/access_tokens \
            | jq -r .token)

          echo "TOKEN=$TOKEN" >> $GITHUB_ENV
